services:
  - type: web
    name: django-web
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py tailwind build && python manage.py populate_tasks && python manage.py populate_proyects"
    startCommand: "gunicorn Tareas_Casa.wsgi:Tareas --preload --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        value: postgresql://base_de_datos_casa_user:j86RAEVzqqX6tSdJxO4JYR0jPTZrLtc6@dpg-ctcsdgtumphs73b7prpg-a/base_de_datos_casa
      - key: REDIS_URL
        value: redis://red-ctcs75popnds73ann7r0:6379
      - key: DJANGO_SETTINGS_MODULE
        value: Tareas_Casa.settings