services:
  - type: web
    name: mi-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn Tareas_Casa.wsgi:Tareas --preload"
    
  - type: worker
    name: celery-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A mi_proyecto worker --loglevel=info"

  - type: worker
    name: celery-beat
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A mi_proyecto beat --loglevel=info"
