# Generated by Django 5.1.4 on 2024-12-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0002_proyectos'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
